/*
 * This source file was generated by the Gradle 'init' task
 */
package shape_drawer;

import shape_drawer.window.MyWindow;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        MyWindow window = new MyWindow(); // creates
                                          // window

        window.ShowWindow();
    }
}
